#!/usr/bin/env python3
"""
Scan a characters directory and emit generated/wasm_character_manifest.cpp for Emscripten.

During a regular web build, build-web.sh converts character BMPs to JPEG in a
temporary directory first, then calls this script with --ext jpg so the
generated manifest lists .jpg filenames (much smaller than .bmp for Vercel).

For desktop the manifest is unused; Allegro scans the filesystem directly.

Run automatically from build-web.sh before emcc.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


def repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


def cpp_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def collect_manifest(characters_dir: Path, ext: str) -> dict[str, list[str]]:
    """Return {slug: [filename, …]} sorted numerically for files with *ext*."""
    ext_dot = "." + ext.lower().lstrip(".")
    out: dict[str, list[str]] = {}
    for sub in sorted(characters_dir.iterdir()):
        if not sub.is_dir() or sub.name.startswith("."):
            continue
        slug = sub.name
        names = [
            p.name
            for p in sub.iterdir()
            if p.is_file() and p.suffix.lower() == ext_dot
        ]
        if not names:
            continue
        pat = re.compile(
            rf"^{re.escape(slug)}_(\d+){re.escape(ext_dot)}$", re.IGNORECASE
        )

        def key(n: str, _pat: re.Pattern = pat) -> tuple:
            mo = _pat.match(n)
            return (0, int(mo.group(1))) if mo else (1, n.lower())

        out[slug] = sorted(names, key=key)
    return out


def emit_cpp(characters_dir: Path, out_path: Path, ext: str) -> None:
    m = collect_manifest(characters_dir, ext)
    slugs_sorted = sorted(m.keys())

    lines: list[str] = [
        "// AUTO-GENERATED by scripts/generate_wasm_character_manifest.py — do not edit.",
        "",
        '#include "wasm_character_manifest.hpp"',
        "",
        "#include <string>",
        "#include <vector>",
        "",
        "namespace {",
        "",
        "std::vector<std::string> files_for_slug_impl(const std::string &slug) {",
    ]

    for slug in slugs_sorted:
        files = m[slug]
        if len(files) == 1:
            lines.append(
                f'  if (slug == "{cpp_escape(slug)}") return {{"{cpp_escape(files[0])}"}};'
            )
        else:
            lines.append(f'  if (slug == "{cpp_escape(slug)}")')
            lines.append("    return {")
            for i, f in enumerate(files):
                comma = "," if i < len(files) - 1 else ""
                lines.append(f'            "{cpp_escape(f)}"{comma}')
            lines.append("           };")

    lines.append("  return {};")
    lines.append("}")
    lines.append("")
    lines.append("} // namespace")
    lines.append("")
    lines.append("std::vector<std::string> wasm_get_bmps_for_slug(const std::string &slug) {")
    lines.append("  return files_for_slug_impl(slug);")
    lines.append("}")
    lines.append("")
    lines.append("void wasm_scan_character_slugs(std::vector<std::string> &out) {")
    lines.append("  out = {")
    for i, s in enumerate(slugs_sorted):
        comma = "," if i < len(slugs_sorted) - 1 else ""
        lines.append(f'      "{cpp_escape(s)}"{comma}')
    lines.append("  };")
    lines.append("}")
    lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    root = repo_root()
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--characters",
        type=Path,
        default=root / "assets/characters",
        help="Path to characters directory (default: <repo>/assets/characters)",
    )
    ap.add_argument(
        "--ext",
        default="bmp",
        help="File extension to scan for and list in the manifest (default: bmp)",
    )
    ap.add_argument(
        "--out",
        type=Path,
        default=root / "generated/wasm_character_manifest.cpp",
        help="Output .cpp path (default: <repo>/generated/wasm_character_manifest.cpp)",
    )
    args = ap.parse_args()
    ch = args.characters.resolve()
    if not ch.is_dir():
        print(f"ERROR: not a directory: {ch}", file=sys.stderr)
        return 1
    emit_cpp(ch, args.out.resolve(), args.ext)
    try:
        rel = args.out.resolve().relative_to(root)
    except ValueError:
        rel = args.out.resolve()
    print(f"Wrote {rel}  (ext=.{args.ext.lstrip('.')}, {len(collect_manifest(ch, args.ext))} characters)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
