#!/usr/bin/env python3
"""
Scan assets/characters/ and emit generated/wasm_character_manifest.cpp for Emscripten.

Uses the same rules as scripts/import_tmp_to_characters.py (collect_manifest).

Run automatically from build-web.sh before emcc.
"""

from __future__ import annotations

import argparse
import importlib.util
import sys
from pathlib import Path


def repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


def load_collect_manifest():
    itc_path = Path(__file__).resolve().parent / "import_tmp_to_characters.py"
    spec = importlib.util.spec_from_file_location("import_tmp_to_characters", itc_path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Cannot load {itc_path}")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod.collect_manifest


def cpp_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def emit_cpp(characters_dir: Path, out_path: Path) -> None:
    collect_manifest = load_collect_manifest()
    m = collect_manifest(characters_dir)
    slugs_sorted = sorted(m.keys())

    lines: list[str] = [
        "// AUTO-GENERATED by scripts/generate_wasm_character_manifest.py — do not edit.",
        "",
        '#include "wasm_character_manifest.hpp"',
        "",
        "#include <string>",
        "#include <vector>",
        "",
        "namespace {",
        "",
        "std::vector<std::string> bmps_for_slug_impl(const std::string &slug) {",
    ]

    for slug in slugs_sorted:
        files = m[slug]
        if len(files) == 1:
            lines.append(
                f'  if (slug == "{cpp_escape(slug)}") return {{"{cpp_escape(files[0])}"}};'
            )
        else:
            lines.append(f'  if (slug == "{cpp_escape(slug)}")')
            lines.append("    return {")
            for i, f in enumerate(files):
                comma = "," if i < len(files) - 1 else ""
                lines.append(f'            "{cpp_escape(f)}"{comma}')
            lines.append("           };")

    lines.append("  return {};")
    lines.append("}")
    lines.append("")
    lines.append("} // namespace")
    lines.append("")
    lines.append("std::vector<std::string> wasm_get_bmps_for_slug(const std::string &slug) {")
    lines.append("  return bmps_for_slug_impl(slug);")
    lines.append("}")
    lines.append("")
    lines.append("void wasm_scan_character_slugs(std::vector<std::string> &out) {")
    lines.append("  out = {")
    for i, s in enumerate(slugs_sorted):
        comma = "," if i < len(slugs_sorted) - 1 else ""
        lines.append(f'      "{cpp_escape(s)}"{comma}')
    lines.append("  };")
    lines.append("}")
    lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    root = repo_root()
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--characters",
        type=Path,
        default=root / "assets/characters",
        help="Path to assets/characters (default: <repo>/assets/characters)",
    )
    ap.add_argument(
        "--out",
        type=Path,
        default=root / "generated/wasm_character_manifest.cpp",
        help="Output .cpp path (default: <repo>/generated/wasm_character_manifest.cpp)",
    )
    args = ap.parse_args()
    ch = args.characters.resolve()
    if not ch.is_dir():
        print(f"ERROR: not a directory: {ch}", file=sys.stderr)
        return 1
    emit_cpp(ch, args.out.resolve())
    print(f"Wrote {args.out.resolve().relative_to(root)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
